server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  ## Routes for Employee and Department Service
  cloud:
    gateway:
      # Automatically Create Routes
      #discovery:
      #  locator:
      #    enabled: true
      #    lower-case-service-id: true
      routes:
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
          - Path=/api/v1/employees/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/v1/departments/**

#logging:
#  level:
#    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG


eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/

# Logging Config
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.web: debug
