# Server Port
server:
  port: 8083

# Spring Configuration
spring:
  application:
    name: ORGANIZATION-SERVICE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: s3cr3t
    url: jdbc:postgresql://localhost:5432/organizationDB